export const newsData = {
  status: "success",
  totalResults: 116,
  results: [
    {
      rate: 5,
      article_id: "bbf54f6fcf54decb5d81ed53095e834c",
      title: "德國看特朗普上任",
      link: "https://www.rfi.fr/tw/%E6%AD%90%E6%B4%B2/20250120-%E5%BE%B7%E5%9C%8B%E7%9C%8B%E7%89%B9%E6%9C%97%E6%99%AE%E4%B8%8A%E4%BB%BB",
      keywords: [
        "歐洲"
      ],
      creator: [
        "© Chip Somodevilla / via Reuters",
        "柏林特約記者 丹蘭"
      ],
      video_url: null,
      description: "美國總統特朗普周一就職上任,德國自然極為關注。",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2025-01-20 18:22:29",
      pubDateTZ: "UTC",
      image_url: "https://s.rfi.fr/media/display/cbdbdd1a-d756-11ef-81e1-005056bf30b7/w:1024/p:16x9/2025-01-20T174329Z_1132319148_RC2TDCAQIYAD_RTRMADP_3_USA-TRUMP-INAUGURATION.JPG",
      source_id: "rfi_fr",
      source_priority: 8490,
      source_name: "Rfi",
      source_url: "https://www.rfi.fr/en/france",
      source_icon: "https://i.bytvi.com/domain_icons/rfi_fr.png",
      language: "chinese",
      country: [
        "montenegro",
        "bosnia and herzegovina",
        "cyprus",
        "united kingdom",
        "albania",
        "malta",
        "ireland",
        "macedonia",
        "spain",
        "moldova",
        "france",
        "germany",
        "san marino",
        "switzerland",
        "poland",
        "netherland",
        "hungary",
        "italy",
        "belgium",
        "austria",
        "greece",
        "russia",
        "sweden",
        "norway",
        "portugal",
        "romania",
        "serbia",
        "bulgaria",
        "czech republic",
        "latvia",
        "lithuania",
        "slovakia",
        "slovenia",
        "ukraine",
        "andorra",
        "kosovo",
        "liechtenstein",
        "finland",
        "monaco",
        "vatican",
        "belarus",
        "denmark",
        "estonia",
        "luxembourg",
        "croatia",
        "iceland"
      ],
      category: [
        "top"
      ],
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
      duplicate: false
    },
    {
      rate: 3,
      article_id: "794cdcd5cdff07e947a7b435c66a315b",
      title: "6.4 magnitude earthquake jolts southern Taiwan",
      link: "https://www.indiatodayne.in/international/story/64-magnitude-earthquake-jolts-southern-taiwan-1157851-2025-01-20",
      keywords: null,
      creator: null,
      video_url: null,
      description: "A 6.4 magnitude earthquake shook southern Taiwan, with tremors reaching Taipei. Minor damage reported and evacuations were carried out.",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2025-01-20 17:45:07",
      pubDateTZ: "UTC",
      image_url: "https://cf-img-a-in.tosshub.com/lingo/itne/images/story/202501/678e8b40a66c3-representational-image-024914651-16x9.jpg?size=948%3A533",
      source_id: "indiatodayne",
      source_priority: 387022,
      source_name: "Indiatoday Ne",
      source_url: "https://www.indiatodayne.in",
      source_icon: null,
      language: "english",
      country: [
        "india"
      ],
      category: [
        "top"
      ],
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
      duplicate: true
    },
    {
      article_id: "3a484d034a0421940bb9999b97b6fdaa",
      title: "分析:特朗普強勢回歸將給全球帶來四年“顛簸期”",
      link: "https://www.rfi.fr/tw/%E5%B0%88%E6%AC%84%E6%AA%A2%E7%B4%A2/%E5%9C%8B%E9%9A%9B%E7%B8%B1%E6%A9%AB/20250120-%E5%88%86%E6%9E%90-%E7%89%B9%E6%9C%97%E6%99%AE%E5%9B%9E%E6%AD%B8%E5%B0%87%E7%B5%A6%E5%85%A8%E7%90%83%E5%B8%B6%E4%BE%86%E5%9B%9B%E5%B9%B4-%E9%A1%9B%E7%B0%B8%E6%9C%9F",
      keywords: [
        "國際縱橫"
      ],
      creator: [
        "艾米"
      ],
      video_url: null,
      description: "美國當選總統特朗普就職典禮於1月20日在華盛頓舉行受到全球聚焦。特朗普重返白宮四年很可能會再次打破本已脆弱的全球平衡。特朗普的上台會給歐洲帶來什麼威脅?中美之間關係如何發展等等都是廣為討論和分析的話題。本次國際縱橫專欄專訪法國中國及國際問題專家菲利普·勒-科爾( Philippe Le Corre),請他做出相關解讀。",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2025-01-20 15:47:39",
      pubDateTZ: "UTC",
      image_url: "https://s.rfi.fr/media/display/3e793964-d741-11ef-b168-005056a90284/w:1024/p:16x9/AP25020529808467.jpg",
      source_id: "rfi_fr",
      source_priority: 8490,
      source_name: "Rfi",
      source_url: "https://www.rfi.fr/en/france",
      source_icon: "https://i.bytvi.com/domain_icons/rfi_fr.png",
      language: "chinese",
      country: [
        "honduras",
        "united states of america",
        "el salvador",
        "jamaica",
        "canada",
        "haiti",
        "barbados",
        "mexico",
        "argentina",
        "netherland",
        "dominica",
        "cayman islands",
        "nicaragua",
        "colombia",
        "brazil",
        "cuba",
        "bahamas",
        "belize",
        "grenada",
        "venezuela",
        "peru",
        "guyana",
        "suriname",
        "chile",
        "ecuador",
        "puerto rico",
        "dominican republic",
        "costa rica",
        "bolivia",
        "paraguay",
        "panama",
        "guatemala",
        "uruguay"
      ],
      category: [
        "top"
      ],
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
      duplicate: false
    },
    {
      rate: 4,
      article_id: "62a3b776fe83c5af6058a7e764de07bf",
      title: "歐盟據報考慮撤銷一樁對華貿易訴訟 立陶宛總統促歐委會莫放棄",
      link: "https://www.rfi.fr/tw/%E6%AD%90%E6%B4%B2/20250120-%E6%AD%90%E7%9B%9F%E6%93%9A%E5%A0%B1%E8%80%83%E6%85%AE%E6%92%A4%E9%8A%B7%E4%B8%80%E6%A8%81%E5%B0%8D%E8%8F%AF%E8%B2%BF%E6%98%93%E8%A8%B4%E8%A8%9F-%E7%AB%8B%E9%99%B6%E5%AE%9B%E7%B8%BD%E7%B5%B1%E6%95%A6%E4%BF%83%E6%AD%90%E5%A7%94%E6%9C%83%E8%8E%AB%E6%94%BE%E6%A3%84",
      keywords: [
        "歐洲"
      ],
      creator: [
        "© 美聯社圖片",
        "弗林"
      ],
      video_url: null,
      description: "立陶宛總統瑙塞達(Gitanas Nauseda)呼籲歐盟委員會繼續對中國涉嫌針對立陶宛的脅迫活動進行國際貿易調查。瑙塞達發表評論前,彭博社周五報導稱歐盟正考慮放棄目前暫停的世貿組織案件。",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2025-01-20 15:26:29",
      pubDateTZ: "UTC",
      image_url: "https://s.rfi.fr/media/display/9d308dec-d73f-11ef-96ab-005056a97e36/w:1024/p:16x9/AP24291261744604-1.jpg",
      source_id: "rfi_fr",
      source_priority: 8490,
      source_name: "Rfi",
      source_url: "https://www.rfi.fr/en/france",
      source_icon: "https://i.bytvi.com/domain_icons/rfi_fr.png",
      language: "chinese",
      country: [
        "montenegro",
        "bosnia and herzegovina",
        "cyprus",
        "united kingdom",
        "albania",
        "malta",
        "ireland",
        "macedonia",
        "spain",
        "moldova",
        "france",
        "germany",
        "san marino",
        "switzerland",
        "poland",
        "netherland",
        "hungary",
        "italy",
        "belgium",
        "austria",
        "greece",
        "russia",
        "sweden",
        "norway",
        "portugal",
        "romania",
        "serbia",
        "bulgaria",
        "czech republic",
        "latvia",
        "lithuania",
        "slovakia",
        "slovenia",
        "ukraine",
        "andorra",
        "kosovo",
        "liechtenstein",
        "finland",
        "monaco",
        "vatican",
        "belarus",
        "denmark",
        "estonia",
        "luxembourg",
        "croatia",
        "iceland"
      ],
      category: [
        "top"
      ],
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
      duplicate: false
    },
    {
      rate: 2,
      article_id: "a25f22f78f640f66a12db6f3fbf87073",
      title: "法國總理警告:或將被美國特朗普新政策“擊垮”",
      link: "https://www.rfi.fr/tw/%E4%B8%AD%E5%9C%8B/20250120-%E6%B3%95%E5%9C%8B%E7%B8%BD%E7%90%86%E8%AD%A6%E5%91%8A-%E6%88%96%E5%B0%87%E8%A2%AB%E7%BE%8E%E5%9C%8B%E7%89%B9%E6%9C%97%E6%99%AE%E6%96%B0%E6%94%BF%E7%AD%96-%E6%93%8A%E5%9E%AE",
      keywords: [
        "中國"
      ],
      creator: [
        "© Abdul Saboor / Reuters",
        "羅拉"
      ],
      video_url: null,
      description: "法國總理貝魯今天警告,如果包括法國在內的歐盟不採取應對措施,或將被特朗普新政府出台的政策“擊垮”,歐盟面臨美國和中國雙重挑戰。",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2025-01-20 15:10:05",
      pubDateTZ: "UTC",
      image_url: "https://s.rfi.fr/media/display/3cdd747a-d193-11ef-ac53-005056bfb2b6/w:1024/p:16x9/2025-01-03T114150Z_1060796329_RC292CAEN35R_RTRMADP_3_FRANCE-POLITICS.JPG",
      source_id: "rfi_fr",
      source_priority: 8490,
      source_name: "Rfi",
      source_url: "https://www.rfi.fr/en/france",
      source_icon: "https://i.bytvi.com/domain_icons/rfi_fr.png",
      language: "chinese",
      country: [
        "china"
      ],
      category: [
        "top"
      ],
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
      duplicate: false
    },
    {
      article_id: "1f6d05ddef1124db7dd1709336db1c95",
      title: "美國華人如何看特朗普回歸?",
      link: "https://www.rfi.fr/tw/%E5%B0%88%E6%AC%84%E6%AA%A2%E7%B4%A2/%E8%A6%81%E8%81%9E%E8%A7%A3%E8%AA%AA/20250120-%E7%BE%8E%E5%9C%8B%E8%8F%AF%E4%BA%BA%E5%A6%82%E4%BD%95%E7%9C%8B%E7%89%B9%E6%9C%97%E6%99%AE%E5%9B%9E%E6%AD%B8",
      keywords: [
        "要聞解說"
      ],
      creator: [
        "艾米"
      ],
      video_url: null,
      description: "美國當選總統特朗普將於周一(1月20號)宣誓就任,就職典禮將於當地時間中午(格林威治標準時間 17:00)在美國國會大廈圓形大廳內舉行。由於天氣極寒,就職典禮 40 年來首次移至室內舉行。",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2025-01-20 14:55:50",
      pubDateTZ: "UTC",
      image_url: "https://s.rfi.fr/media/display/feaf171c-d732-11ef-be8b-005056bf30b7/w:1024/p:16x9/ap25019812783249.jpg",
      source_id: "rfi_fr",
      source_priority: 8490,
      source_name: "Rfi",
      source_url: "https://www.rfi.fr/en/france",
      source_icon: "https://i.bytvi.com/domain_icons/rfi_fr.png",
      language: "chinese",
      country: [
        "honduras",
        "united states of america",
        "el salvador",
        "jamaica",
        "canada",
        "haiti",
        "barbados",
        "mexico",
        "argentina",
        "netherland",
        "dominica",
        "cayman islands",
        "nicaragua",
        "colombia",
        "brazil",
        "cuba",
        "bahamas",
        "belize",
        "grenada",
        "venezuela",
        "peru",
        "guyana",
        "suriname",
        "chile",
        "ecuador",
        "puerto rico",
        "dominican republic",
        "costa rica",
        "bolivia",
        "paraguay",
        "panama",
        "guatemala",
        "uruguay"
      ],
      category: [
        "top"
      ],
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
      duplicate: false
    },
    {
      article_id: "71176ad76c34bffe9510f00e7ee695f2",
      title: "Viettel sẽ phóng được vệ tinh và sản xuất chip bán dẫn vào năm 2030",
      link: "https://cafebiz.vn/viettel-se-phong-duoc-ve-tinh-va-san-xuat-chip-ban-dan-vao-nam-2030-176250120214837401.chn",
      keywords: null,
      creator: null,
      video_url: null,
      description: "Viettel được trực tiếp Bộ Quốc phòng chỉ đạo, giao nghiên cứu, sản xuất chế tạo, phóng được vệ tinh vào năm 2030. Đây cũng là mốc để Việt Nam có những sản phẩm vệ tinh đầu tiên.",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2025-01-20 14:47:00",
      pubDateTZ: "UTC",
      image_url: "https://cafebiz.cafebizcdn.vn/zoom/700_438/162123310254002176/2025/1/20/avatar1737384458102-17373844639991093129730.jpg",
      source_id: "cafebiz",
      source_priority: 619255,
      source_name: "Cafebiz",
      source_url: "https://cafebiz.vn",
      source_icon: "https://i.bytvi.com/domain_icons/cafebiz.png",
      language: "vietnamese",
      country: [
        "vietnam"
      ],
      category: [
        "business"
      ],
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
      duplicate: true
    },
    {
      article_id: "a3d2a09ac4fef96402d0529d0f8156e8",
      title: "特朗普就職日 馬克龍提出自己的“軍事指導方針”",
      link: "https://www.rfi.fr/tw/%E5%B0%88%E6%AC%84%E6%AA%A2%E7%B4%A2/%E6%B3%95%E5%9C%8B%E7%94%9F%E6%B4%BB/20250120-%E7%89%B9%E6%9C%97%E6%99%AE%E5%B0%B1%E8%81%B7%E6%97%A5-%E9%A6%AC%E5%85%8B%E9%BE%8D%E6%8F%90%E5%87%BA%E8%87%AA%E5%B7%B1%E7%9A%84-%E8%BB%8D%E4%BA%8B%E6%8C%87%E5%B0%8E%E6%96%B9%E9%87%9D",
      keywords: [
        "法國生活"
      ],
      creator: [
        "艾娃"
      ],
      video_url: null,
      description: "法國總統馬克龍今天周一表示,將在傳統的為軍方舉辦的新年祝詞儀式上向軍隊提出“他的指導方針”,以應對世界越來越多的威脅,因為在他看來,這需要歐洲自己加強軍事國防的自主性與實力。而馬克龍多年來敦促歐洲真正建立並強化國防,且今天恰逢美國總統特朗普回歸白宮的就職典禮。",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2025-01-20 14:41:22",
      pubDateTZ: "UTC",
      image_url: "https://s.rfi.fr/media/display/845ab1ea-d71b-11ef-8186-005056bf30b7/w:1024/p:16x9/AP24343321403870.jpg",
      source_id: "rfi_fr",
      source_priority: 8490,
      source_name: "Rfi",
      source_url: "https://www.rfi.fr/en/france",
      source_icon: "https://i.bytvi.com/domain_icons/rfi_fr.png",
      language: "chinese",
      country: [
        "france"
      ],
      category: [
        "top"
      ],
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
      duplicate: false
    },
    {
      article_id: "4dd2b9d453107ad8b88d1d6f33077e28",
      title: "Party chief chairs 1st meeting of steering committee for science, technology development",
      link: "https://en.vietnamplus.vn/party-chief-chairs-1st-meeting-of-steering-committee-for-science-technology-development-post308642.vnp",
      keywords: [
        "politics"
      ],
      creator: null,
      video_url: null,
      description: "Party General Secretary To Lam chaired the first meeting of the Central Steering Committee for the Development of Science, Technology, Innovation and Digital Transformation in Hanoi on January 20.NA Chairman clarifies institutional solutions for development of science, technology, innovationPM calls for concerted actions to implement resolution on science, technologyCentral steering committee for sci-tech development, innovation, digital transformation set up",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2025-01-20 14:34:44",
      pubDateTZ: "UTC",
      image_url: "https://mediaen.vietnamplus.vn/images/e43bcfe3564b6c7c48cc9ff9df3778bf2118d4abc347d99b1e883f1afb4eea406d1811f5e396ffb309611b8337595828/to-lam.jpg.webp",
      source_id: "vietnamplus",
      source_priority: 248784,
      source_name: "Vietnam+",
      source_url: "https://www.vietnamplus.vn",
      source_icon: "https://i.bytvi.com/domain_icons/vietnamplus.png",
      language: "english",
      country: [
        "vietnam"
      ],
      category: [
        "top"
      ],
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
      duplicate: false
    },
    {
      article_id: "02b8a730329b15204cb271d84f017cb9",
      title: "Bỏ tiền mua suất ăn, đồ uống nhưng không sử dụng mà 'treo lên': Bắt đầu nở rộ",
      link: "https://cafebiz.vn/bo-tien-mua-suat-an-do-uong-nhung-khong-su-dung-ma-treo-len-bat-dau-no-ro-176250120210921898.chn",
      keywords: null,
      creator: null,
      video_url: null,
      description: "WeTreo đang âm thầm lan tỏa.",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2025-01-20 14:09:00",
      pubDateTZ: "UTC",
      image_url: "https://cafebiz.cafebizcdn.vn/zoom/700_438/162123310254002176/2025/1/20/avatar1737382123388-1737382124167867836783.jpg",
      source_id: "cafebiz",
      source_priority: 619255,
      source_name: "Cafebiz",
      source_url: "https://cafebiz.vn",
      source_icon: "https://i.bytvi.com/domain_icons/cafebiz.png",
      language: "vietnamese",
      country: [
        "vietnam"
      ],
      category: [
        "business"
      ],
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
      ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
      duplicate: true
    }
  ],
  nextPage: "1737382140870383425"
}